services:
  dockhound:
    #image: dockhound:dev
    restart: unless-stopped
    build: Dockhound/
    environment:
      - WLL_token=${WLL_token}
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/Grafana
volumes:
  grafana-storage: {}